# Generated by Django 4.2 on 2023-04-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_client_sales_contact_client_sales_client_and_more'),
        ('contrats', '0002_contract_delete_contrat'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='sales_contact',
            new_name='sales_events',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='support_contact',
            new_name='support_events',
        ),
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
        migrations.AddField(
            model_name='event',
            name='client_events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_events', to='customers.client'),
        ),
        migrations.AddField(
            model_name='event',
            name='contract_events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_events', to='contrats.contract'),
        ),
    ]
